"""Database creation

Revision ID: 488a230b49ec
Revises: 
Create Date: 2024-01-24 13:37:00.048577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488a230b49ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('role',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(), nullable=False),
                        sa.Column('permissions', sa.JSON(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_table('user',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('email', sa.String(), nullable=False),
                        sa.Column('username', sa.String(), nullable=False),
                        sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                        sa.Column('role_id', sa.Integer(), nullable=True),
                        sa.Column('hashed_password', sa.String(), nullable=False),
                        sa.Column('is_active', sa.Boolean(), nullable=False),
                        sa.Column('is_superuser', sa.Boolean(), nullable=False),
                        sa.Column('is_verified', sa.Boolean(), nullable=False),
                        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                        sa.PrimaryKeyConstraint('id')
                        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
